---
title: Siteleaf Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  things:
    title: Things
    output: true
    asdf:
    - asdffffff
    - asdffasdf
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
